### ISSUE TITLE
genre list

### ISSUE THREAD

**Issue by AtomicNess123** [Ximinhan/DeepLearningProject#1]
I am getting

`'Genres' object has no attribute 'list'`

When I do:

```
genres=tmdb.Genres()
# the list() method of the Genres() class returns a listing of all genres in the form of a dictionary.
list_of_genres=genres.list()['genres']
```

Any idea if this has changed?
Thanks.

**Comment by Ximinhan** [comment]
I guess it's movie_list function now, this doc is really out date.
